######################## default configuration ####################
baseURL = "https://noosacafe.onrender.com/"
languageCode = "en-us"
title = "Noosa cafe"
theme = "restaurant-hugo"
summaryLength = "7"
paginate = 6

[markup.goldmark.renderer]
unsafe= true
############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
URL = "css/bootstrap.min.css"
[[params.plugins.css]]
URL = "css/slick.css"
[[params.plugins.css]]
URL = "css/font-awesome.min.css"
[[params.plugins.css]]
URL = "css/animate.min.css"
[[params.plugins.css]]
URL = "css/venobox.css"
[[params.plugins.css]]
URL = "css/main.css"
[[params.plugins.css]]
URL = "css/responsive.css"

# JS Plugins
[[params.plugins.js]]
URL = "js/jquery.min.js"
[[params.plugins.js]]
URL = "js/bootstrap.min.js"
[[params.plugins.js]]
URL = "js/slick.min.js"
[[params.plugins.js]]
URL = "js/wow.min.js"
[[params.plugins.js]]
URL = "js/venobox.min.js"
[[params.plugins.js]]
URL = "js/main.js"

############################## navigation ###############################

[[menu.main]]
name = "Home"
URL = "hero-area"
weight = 1

[[menu.main]]
name = "News"
URL = "about-us"
weight = 2

[[menu.main]]
name = "Our dishes"
URL = "blog"
weight = 3

[[menu.main]]
name = "Menù"
URL = "price"
weight = 4

[[menu.main]]
name = "Order now"
URL = "price"
weight = 5

[[menu.main]]
name = "Contact Us"
URL = "contact-us"
weight = 6


#################### default parameters ################################
[params]
logo = "images/logo.png"
# meta data
author = "Simone"
description = "Noosa social espresso Brisbane"
# google analitycs ID
google_analitycs_id = "214184382"
# copyright
copyright = "Copyright 2020 - All Rights Reserved."

# Preloader
[params.preloader]
enable = true
preloader = "" # use .png , .svg or .gif format

################################### Footer ############################
[params.footer]
enable = true
contactInfoTitle = "CONTACT <span>INFO</span> "
blogTitle = "Our <span>LOCATION</span>"
galleryTitle = "PHOTO <span>STREAM</span>"
socialTitle = "Follow US"

############################ footer contact item
[[params.footer.contactItem]]
title="Telephone"
icon = "fa fa-phone"
content = "+61 7 5447 4393"

[[params.footer.contactItem]]
title="Address"
icon = "fa fa-map-marker"
content = "Shop 2/62 Hastings St, Noosa Heads QLD 4567, Australia"

[[params.footer.contactItem]]
title="E mail"
icon = "fa fa-envelope"
content = "info@noosasocialespresso.com.au"

######################### footer gallery
[[params.footer.gallery]]
image = "images/blog/blog-img-1.jpg"

[[params.footer.gallery]]
image = "images/blog/blog-img-2.jpg"

[[params.footer.gallery]]
image = "images/blog/blog-img-3.jpg"


######################## Social Icon 
[[params.footer.socialLink]]
icon = "facebook"
link = "https://www.facebook.com/noosasocialespresso/"

[[params.footer.socialLink]]
icon = "instagram"
link = "https://instagram.com/noosa.social?igshid=ehc5u9lf9tyr"